### ISSUE TITLE
Update the codesandbox's package version

### ISSUE THREAD

**Issue by 3aluw** [Leecason/vue-rough-notation#44]
the provided sandbox demo needs an update. it log an error:  't is not a function  -at Proxy.render (.../node_modules/vue-rough-notation/dist/vue-rough-notation.esm.js:1593:23' ).

The problem disappeared after I updated the package to 1.0.4.

![Captu3re](https://github.com/Leecason/vue-rough-notation/assets/82264545/c575d5a6-6bf6-4d81-b580-eaa5bcfc2660)
